export const members = [
  {
    id: 1,
    image: "/src/assets/images/assignee.png",
    fullName: "Nazira",
    email: "nazira@gmail.com",
    type: "board",
  },
  {
    id: 2,
    image: "/src/assets/images/assignee.png",
    fullName: "Aibek",
    email: "aibek@gmail.com",
    type: "workspace",
  },
  {
    id: 3,
    image: "/src/assets/images/assignee.png",
    fullName: "Aidana",
    email: "aidana@gmail.com",
    type: "board",
  },
  {
    id: 4,
    image: "/src/assets/images/assignee.png",
    fullName: "Nazira",
    email: "nazira@gmail.com",
    type: "workspace",
  },
  {
    id: 5,
    image: "/src/assets/images/assignee.png",
    fullName: "Bekzat",
    email: "bekzat@gmail.com",
    type: "board",
  },
  {
    id: 6,
    image: "/src/assets/images/assignee.png",
    fullName: "Dana",
    email: "dana@gmail.com",
    type: "workspace",
  },
  {
    id: 7,
    image: "/src/assets/images/assignee.png",
    fullName: "Temirlan",
    email: "temirlan@gmail.com",
    type: "board",
  },
  {
    id: 8,
    image: "/src/assets/images/assignee.png",
    fullName: "Ainura",
    email: "ainura@gmail.com",
    type: "workspace",
  },
  {
    id: 9,
    image: "/src/assets/images/assignee.png",
    fullName: "Erbol",
    email: "erbol@gmail.com",
    type: "board",
  },
  {
    id: 10,
    image: "/src/assets/images/assignee.png",
    fullName: "Samira",
    email: "samira@gmail.com",
    type: "workspace",
  },
  {
    id: 11,
    image: "/src/assets/images/assignee.png",
    fullName: "Adilet",
    email: "adilet@gmail.com",
    type: "board",
  },
  {
    id: 12,
    image: "/src/assets/images/assignee.png",
    fullName: "Bermet",
    email: "bermet@gmail.com",
    type: "workspace",
  },
  {
    id: 13,
    image: "/src/assets/images/assignee.png",
    fullName: "Almaz",
    email: "almaz@gmail.com",
    type: "board",
  },
  {
    id: 14,
    image: "/src/assets/images/assignee.png",
    fullName: "Chyngyz",
    email: "chyngyz@gmail.com",
    type: "workspace",
  },
  {
    id: 15,
    image: "/src/assets/images/assignee.png",
    fullName: "Meerim",
    email: "meerim@gmail.com",
    type: "board",
  },
  {
    id: 16,
    image: "/src/assets/images/assignee.png",
    fullName: "Ruslan",
    email: "ruslan@gmail.com",
    type: "workspace",
  },
  {
    id: 17,
    image: "/src/assets/images/assignee.png",
    fullName: "Dastan",
    email: "dastan@gmail.com",
    type: "board",
  },
  {
    id: 18,
    image: "/src/assets/images/assignee.png",
    fullName: "Asel",
    email: "asel@gmail.com",
    type: "workspace",
  },
  {
    id: 19,
    image: "/src/assets/images/assignee.png",
    fullName: "Kanat",
    email: "kanat@gmail.com",
    type: "board",
  },
  {
    id: 20,
    image: "/src/assets/images/assignee.png",
    fullName: "Aizat",
    email: "aizat@gmail.com",
    type: "workspace",
  },
];
