export const notificationsData = [
  {
    id: 1,
    name: "Nazira Nazirova",
    title2: "Name of the column",
    title: "Title on the board",
    text: "Moved to list Done",
    time: "Sep 15 at 13:23 PM",
    read: false,
    background: "#ffffff",
  },
  {
    id: 2,
    name: "Reminder",
    title: "Title on the board",
    title2: "Name of the column",
    text: "Was due 10 min ago",
    time: "Sep 15 at 13:23 PM",
    read: false,
    background: "#ffffff",
  },
  {
    id: 3,
    name: "Nazira Nazirova'",
    title: "Title on the board",
    title2: "Name of the column",
    text: "My God, let me not burn out on this task",
    time: "Sep 15 at 13:23 PM",
    read: false,
    background: "#ffffff",
  },
];
